using UnityEngine.Audio;
using System.Collections;
using UnityEngine;

public class AudioManager : MonoBehaviour
{
    #region Static Instance
    private static AudioManager _instance;
    public static AudioManager Instance
    {
        get
        {
            if(_instance == null)
            {
                _instance = FindObjectOfType<AudioManager>();
                if(_instance == null)
                {
                    _instance = new GameObject("Spawned AudioManager", typeof(AudioManager)).GetComponent<AudioManager>();
                }
            }
            return _instance;
        }
        private set
        {
            _instance = value;
        }
    }
    #endregion

    #region Fields
    private AudioSource musicSource;
    private AudioSource musicSource2;
    private AudioSource sfxSource;
    private AudioSource sfxWalklingSource;
    private AudioSource sfxSlidingSource;

    private bool firstMusicSourceIsPlaying;
    #endregion

    private void Awake()
    {
        DontDestroyOnLoad(this.gameObject);

        musicSource = this.gameObject.AddComponent<AudioSource>();
        musicSource2 = this.gameObject.AddComponent<AudioSource>();
        sfxSource = this.gameObject.AddComponent<AudioSource>();
        sfxWalklingSource = this.gameObject.AddComponent<AudioSource>();
        sfxSlidingSource = this.gameObject.AddComponent<AudioSource>();

        musicSource.loop = true;
        musicSource2.loop = true;
    }

    private void LateUpdate()
    {
        CheckTimeScale();
    }

    public void PlayMusic(AudioClip musicClip)
    {
        AudioSource activeSource = (firstMusicSourceIsPlaying) ? musicSource : musicSource2;

        activeSource.clip = musicClip;
        activeSource.volume = 1;
        activeSource.Play();
    }
    public bool MusicIsPlaying() { return musicSource.isPlaying; }
    public void PlayMusicWithFade(AudioClip newClip, float transitionTime = 1.0f)
    {
        AudioSource activeSource = (firstMusicSourceIsPlaying) ? musicSource : musicSource2;
        StartCoroutine(UpdateMusicWithFade(activeSource, newClip, transitionTime));
    }
    public void PlayMusicWithCrossFade(AudioClip musicClip, float transitionTime = 1.0f)
    {
        AudioSource activeSource = (firstMusicSourceIsPlaying) ? musicSource : musicSource2;
        AudioSource newSource = (firstMusicSourceIsPlaying) ? musicSource2 : musicSource;

        firstMusicSourceIsPlaying = !firstMusicSourceIsPlaying;

        newSource.clip = musicClip;
        newSource.Play();
        StartCoroutine(UpdateMusicWithCrossFade(activeSource, newSource, transitionTime));
    }
    private IEnumerator UpdateMusicWithFade(AudioSource activeSource, AudioClip newClip, float transitionTime)
    {
        if (!activeSource.isPlaying)
            activeSource.Play();

        float t = 0.0f;

        for (t = 0; t < transitionTime; t += Time.deltaTime)
        {
            activeSource.volume = (1 - (t / transitionTime));
            yield return null;
        }

        activeSource.Stop();
        activeSource.clip = newClip;
        activeSource.Play();


        for (t = 0; t < transitionTime; t += Time.deltaTime)
        {
            activeSource.volume = (t / transitionTime);
            yield return null;
        }
    }
    private IEnumerator UpdateMusicWithCrossFade(AudioSource original, AudioSource newSource, float transitionTime)
    {
        float t = 0.0f;

        for (t = 0; t <= transitionTime; t += Time.deltaTime)
        {
            original.volume = (1 - (t / transitionTime));
            newSource.volume = (t / transitionTime);
            yield return null;
        }

        original.Stop();
    }

    public void PlaySFX(AudioClip clip)
    {
        sfxSource.PlayOneShot(clip);
    }
    public void PlayWalkingSFX(AudioClip clip)
    {
        StopSlidingSFX();
        sfxWalklingSource.volume = Random.Range(0.8f, 1f);
        sfxWalklingSource.pitch = Random.Range(0.8f, 1.1f);
        sfxWalklingSource.PlayOneShot(clip);
    }
    public void PlaySlidingSFX(AudioClip clip)
    {
        //StopWalkingSFX();
        sfxSlidingSource.volume = Random.Range(0.8f, 1f);
        sfxSlidingSource.pitch = Random.Range(0.8f, 1.1f);
        sfxSlidingSource.PlayOneShot(clip);

    }
    public void PlaySFX(AudioClip clip, float volume)
    {
        sfxSource.PlayOneShot(clip, volume);
    }

    public bool SFXIsPlaying() { return sfxSource.isPlaying; }
    public void StopSlidingSFX()
    {
        sfxSlidingSource.Stop();

    }
    public void StopWalkingSFX()
    {
        sfxWalklingSource.Stop();
    }
    public bool WalkingSFXIsPlaying() { return sfxWalklingSource.isPlaying; }
    public bool SlidingSFXIsPlaying() { return sfxSlidingSource.isPlaying; }

    public void SetMusicVolume(float volume)
    {
        musicSource.volume = volume;
        musicSource2.volume = volume;
    }
    public void SetSFXVolume(float volume)
    {
        sfxSource.volume = volume;
    }

    public void CheckTimeScale()
    {
        musicSource.pitch = Time.timeScale;
        musicSource2.pitch = Time.timeScale;
        sfxSource.pitch = Time.timeScale;
        sfxWalklingSource.pitch = Time.timeScale;
        sfxSlidingSource.pitch = Time.timeScale;
    }
}
